*** Variables ***
# Home Page Locators
${menuMore}       //a[@id='btnMenuMore']    # Menu More on home page
${login_Register_Menu}    //a[@class='appWrapper-UserMenuItem-above']    # Login menu in menu when user click on menu more
${user_rewards_point}    //a[@href='https://www.chotot.com/uu-dai/diem-tot/da-nhan']
# Login Page locators
${telephone}      //input[@type='tel']    # Phone number input on login page
${password}       //input[@type='password']    # Password input field on login page
${btnlogin}       //button[@type='submit']    # Login button on Login page
